sensor_tf_configs:
  - parent_frame: base_footprint
    child_frame: cepton
    position: [3.5, 0.0, 0.55]
    orientation: [-0.03, 0.0, -1.5707]
  - parent_frame: cepton
    child_frame: cepton_0
    position: [0.0, 0.0, 0.0]
    orientation: [0.0, 0.0, 0.0]
  - parent_frame: cepton
    child_frame: ouster1
    position: [-0.549383, -2.2611, 0.818264]
    orientation: [0.0225254, 0.220428, 2.24367]
  - parent_frame: ouster1
    child_frame: ouster2
    position: [-1.615, -0.0261436, -0.304749]
    orientation: [-0.0610801, -0.430309, 0.141324]
  - parent_frame: base_footprint
    child_frame: lrr
    position: [3.38, 0.0, 0.55]
    orientation: [0.0, 0.0, 0.005]
  - parent_frame: base_footprint
    child_frame: traffic_cam_optical
    position: [2.0, 0.3, 1.2]
    orientation: [0.0, -0.07, -0.017]
  - parent_frame: traffic_cam_optical
    child_frame: traffic_cam
    position: [0.0, 0.0, 0.0]
    orientation: [-1.5707, 0.0, -1.5707]
  - parent_frame: traffic_cam
    child_frame: camera
    position: [0.0, 0.0, 0.0]
    orientation: [0.0, 0.0, 0.0]
